# EfficientTeacher by Alibaba Cloud 

project: 'dsa_yolov7_ssod'
adam: False
epochs: 700
weights: 'weights/efficient-noremove.pt'
prune_finetune: False
linear_lr: True
find_unused_parameters: True


hyp:
  lr0: 0.001
  hsv_h: 0.015
  hsv_s: 0.7
  hsv_v: 0.4
  lrf: 1.0
  scale: 0.9
  burn_epochs: 0
  no_aug_epochs: 0
  # mixup: 0.1
  warmup_epochs: 3

Model:
  depth_multiple: 1.00  # model depth multiple
  width_multiple: 1.00  # layer channel multiple
  Backbone: 
    name: 'YoloV7'
    activation: 'SiLU'
  Neck: 
    name: 'YoloV7' 
    in_channels: [512, 1024, 1024]
    out_channels: [256, 512, 1024]
    activation: 'SiLU'
  Head: 
    name: 'YoloV7'
    activation: 'SiLU'
  anchors: [[12,16, 19,36, 40,28],[36,75, 76, 55, 72, 146],[142, 110, 192,243, 459,401]] # P5/32]
Loss:
  type: 'ComputeLoss'
  cls: 0.3
  obj: 0.7
  anchor_t: 4.0

Dataset:
  data_name: 'yolov7_ssod'
  train: datasets/integrate_for_training/labeled_train.txt 
  val: datasets/integrate_for_training/val.txt   
  test: datasets/integrate_for_training/val.txt  
  target: datasets/integrate_for_training/unlabeled_train.txt 
  nc: 14  # number of classes
  np: 0 #number of keypoints
  names: [ "go","goForward", "stop","warn", "off", "goLeft","goForward_left",
"right", "goForward_right", "goForward_left_right", "goForward_warn", "stop_warn", "warnLeft", "stopLeft"]
  img_size: 640
  batch_size: 8

SSOD:
  train_domain: True
  nms_conf_thres: 0.1
  nms_iou_thres: 0.65
  teacher_loss_weight: 1.0
  cls_loss_weight: 0.3
  box_loss_weight: 0.05
  obj_loss_weight: 0.7
  loss_type: 'ComputeStudentMatchLoss'
  ignore_thres_low: 0.1
  ignore_thres_high: 0.6
  uncertain_aug: True
  use_ota: False
  multi_label: False
  ignore_obj: False
  pseudo_label_with_obj: True
  pseudo_label_with_bbox: True
  pseudo_label_with_cls: False
  with_da_loss: False
  da_loss_weights: 0.01
  epoch_adaptor: True
  resample_high_percent: 0.25
  resample_low_percent: 0.99
  ema_rate: 0.999
  cosine_ema: True
  imitate_teacher: False
  # dynamic_thres: True
  ssod_hyp:
    with_gt: False
    mosaic: 1.0
    cutout: 0.5
    autoaugment: 0.5
    scale: 0.8
    degrees: 0.0
    shear: 0.0